#!/bin/bash
#
# Skript, mis arvutab kolmnurga pindala


#Andmete sisestamine, mida skript loeb
echo -n "Sisesta kolmnurga külje A pikkus: "
read a_kylg
echo -n "Sisesta kolmnurga külje B pikkus: "
read b_kylg
echo -n "Sisesta kolmnurga külje C pikkus: "
read c_kylg

#Vastuse arvutamine
p=$( echo "scale=2;($a+$b+$c)/2" | bc ) #Ümbermõõdu arvutamine
pindala=`echo "scale=2;sqrt($p * ($p - $a_kylg) * ($p - $b_kylg) * ( $p - $c_kylg ))" | bc`

#Vastuse väljastamine
echo "Kolmnurga pindala on $pindala"


# Skripti lõpp
