#!/bin/bash
#
# Skript, kuhu on võimalik sisestada oma nime ja see väljastab hilisemalt selle täislauses


echo -n "Sisesta eesnimi ja perekonnanimi: " #Küsib skripti kasutajalt nime
read eesnimi perenimi #Skript võtab arvesse nime
echo "Sinu eesnimi on $eesnimi ja perekonnanimi on $perenimi" #Väljastab sisestatud andmed lauses


# skripti lõpp
